### ISSUE TITLE
"ERROR: bad base mesh" on seemingly valid mesh

### ISSUE THREAD

**Issue by cmbasnett** [gildor2/UEViewer#149]
We are getting this error on a number of our files. This file is from Darkest Hour, a mod of Red Orchestra (Unreal 2.5x). We can view the mesh just fine in our SDK but are unable to view or export the model using umodel.

![image](https://user-images.githubusercontent.com/5035660/72214344-cdd0eb00-34b4-11ea-9b37-c6926eed3885.png)

Here's a shot of what the mesh looks like in our editor:

![image](https://user-images.githubusercontent.com/5035660/72214382-767f4a80-34b5-11ea-9142-12593ee5e6d1.png)

And here's the file: [DH_MillsBomb.zip](https://github.com/gildor2/UEViewer/files/4050225/DH_MillsBomb.zip)

**Comment by gildor2** [comment]
"Bad mesh" here rather means that the mesh appears bad for UE Viewer. It doesn't mean that it's bad for the engine. The reason is that UE Viewer using different data structures for rendering skeletal meshes, compared to the engine. Old versions of UE Viewer just crashed with such meshes, but I converted this to a log message instead.

A bit of details. UE2 is using some "skinning stream" for rendering skeletal meshes. UE Viewer is using data which exists after importing a mesh, but which is not used by the game itself. It seems that _some_ games has a possibility to _strip_ editor data, probably for reducing file size (or for protecting a mesh from extraction). I've inspected UE2 source code and didn't find any possibility to strip this data, so I have no idea how people do that.

**Comment by cmbasnett** [comment]
Interesting. Thanks for the information.

**Comment by cmbasnett** [comment]
I believe we've discovered how these assets managed to lose this information. Within UE2, there is an option to "rename" assets which can be used to move assets from one package to another. It appears that this method strips the assets of the data that umodel uses to render the mesh.

**Comment by gildor2** [comment]
Ah, nice, thank you for letting me know. Could you tell me exactly how to do that withing the editor, so later I'd be able to investigate UT2004 source code for details of what it does?
