### ISSUE TITLE
.psa Female CMF Problem

### ISSUE THREAD

**Issue by josigamer** [gildor2/UEViewer#155]
I encountered a problem when trying to export any female .psa (CMF)

Problem: https://youtu.be/vLHNDswH5Gs

Files I used: https://drive.google.com/file/d/1AFcrOeZs-Nrv7UPwoVxnkx_8mt9WubFa/view?usp=sharing

I tried several female .psa and they all have problems, when I export any CMM file it works but the bones of the male animation are bigger and this spoils the visual.

I checked on the blender console and the amount of bones imported in CMF and CMM were the same and the names of the targets

I tested almost all of the Fortnite CMF emotes and they all have the same error, only the HappySkipping CMF emote worked correctly

**Comment by gildor2** [comment]
I never worked with Blender myself, it would be much more useful if you'd ask such question on the forum instead of github (I've explicitly asked about that in "Please read before ..." topic #113 ). However I'll try to explain the core of the problem - without providing a solution (as I'm not a DCC tool user).

There are animations which are shared between different skeletons. Each animated bone has position and rotation (and sometimes scale - which is NOT supported by UModel). When skeletons has different proportions, position animation will do the issue which you see on the video.
![image](https://user-images.githubusercontent.com/7008904/80871342-0d6a4f80-8cbd-11ea-84c9-bdc55a864c31.png)

Another issue - when the mesh if "packed" into something wrong.
![image](https://user-images.githubusercontent.com/7008904/80871308-e4e25580-8cbc-11ea-9532-200f509b32eb.png)

This is a typical user's mistake. This animation is "additive" and not supported in UModel or any related tool.

Also I'm unsure how did you export animations. PSA files may have multiple animation tracks, Again, I'm unfamiliar with Blender UI for PSA loading, there should be something to select animated track.

May be @Blenux may provide more info on that.

**Comment by Blenux** [comment]
Fortnite_M_Avg_Player_Skeleton is the base skeleton for every animation in Fortnite, then they retarget (plus other stuff like IK's ) on other characters skeletons on top of it, be it either Female or Large or smaller characters, I suggest to watch some Fortnite Animations videos on Youtube that epic have shown a bit to understand it better.

Like so, 

https://www.youtube.com/watch?v=tWVZ6KO4lRs

(There was a better video but cant video currently).

**Comment by abdumatin** [comment]
The animations for female are usually additive when they have been re targeted and are edited inside UE4. To use any animation on a female character that is CMM you just have to add the psa to a AVG base skeleton. Then go back to your female skin and in the animation tabs from the action editor put the animation and then it will be re targeted correctly.

**Comment by gildor2** [comment]
It seems the issue's author has lost interest to it. Closing ...
