### ISSUE TITLE
ERROR: Memory: bad allocation size

### ISSUE THREAD

**Issue by hi5kba** [gildor2/UEViewer#157]
I'm trying to export assets from two games.

i keep getting the "ERROR: Memory: bad allocation size"  followed by a changing string of numbers each time no matter which settings i use. i have studied the Compatibility Table for both games and no setting seem to work.
and before i'm pointed to the Forums (https://www.gildor.org/smf/index.php/topic,6385.0.html) / Google, like Similar past issues. Nada no help there.

I'm using the new relaese: 
UE Viewer for Win32 | Size944.06 KB | Updated20 May, 2020 - 12:28

the two games i am trying to export:
Deliver us the Moon
The Turing Test

*** ERROR: Memory: bad allocation size -482914636 bytes
appMalloc:size=-482914636 (total=2 Mbytes) <- FArray::Empty:1391412879 x 12 <- FPackageFileSummary::Serialize4 <- FPackageFileSummary<<:Ver=0/0 <- UnPackage::UnPackage:Engine/Content/BasicShapes/BasicShapeMaterial.uasset, ver=413/0, game=ue4.6 <- UnPackage::LoadPackage:Engine/Content/BasicShapes/BasicShapeMaterial.uasset <- UIMenuItem::HandleCommand <- UIMenu::Popup <- UIBaseDialog::WndProc <- UIBaseDialog::CustomMessageLoop <- UIBaseDialog::ShowDialog:modal=1, title="Choose a package to open" <- CUmodelApp::ShowPackageUI <- Main:umodel_build=1190

**Comment by gildor2** [comment]
"Deliver to the Moon" has specified version 4.16, you're setting 4.6. What's wrong?
Anyway, in #113 I've asked to _not_ create issues of this kind, this is a _user_ error - not an issue in UModel.

**Comment by hi5kba** [comment]
I’ve tried numerous settings. both Overriding auto detection and setting it to 4.16 & 4.22 that is listed on the compat table. 

Not setting the override gets me the unversioned pop up in which there is no option for either of the two stated. It only has

4.0, 4.1, 4.2, 4.3, 4.4, 4.5 And 4.6. Nothing else.

All ways still gets me the same final “ ERROR: Memory: bad allocation size”

I had no problem in the Past with “Deliver Us the Moon“ however that was with previous versions of Umodel which I no longer have. Thus me thinking it’s a change in code.

**Comment by gildor2** [comment]
Older UModel versions are available here, as a history of umodel.exe (it was mentioned in FAQ). If older version does work, but new one - not, then it's probably a bug.
Anyway, I always suggesting using forum for this kind of conversation, because I'm very rarely checking games myself - other people do that job.

**Comment by gildor2** [comment]
Seems issue author lost interest to the problem. Closing. Feel free to reopen if still needed.

**Comment by Cracko298** [comment]
I don't know if I'm doing something absolutely wrong, But it pops up whenever I extract a model.
SO I wouldn't know if I was doing anything wrong. Probably am, But I just need a bit of guidance is all.

**Comment by gildor2** [comment]
Probably you've set up a wrong engine version, or the game is not supported. You should check the compatibility table and the forum thread about this game.

**Comment by JuanPeiffer** [comment]
Me pasa algo parecido, me aparece esto 
Memory: bad allocation size 1673760496 bytes
appMalloc: size=1673760496 (total=33 Mbytes) <- FArray::Empty: 855307924 x 12 <- FPackageFileSummary::Serialize4 <- FPackageFileSummary<<: Ver=0/0 <- UnPackage::UnPackage: /Engine/Animation/DefaultAnimCurveCompressionSettings.uasset, ver=518/0, game=ue4.24 <- UnPackage::LoadPackage(info): /Engine/Animation/DefaultAnimCurveCompressionSettings.uasset <- ScanContent <- UIMenuItem::HandleCommand <- UIMenu::Popup <- UIBaseDialog::WndProc <- UIBaseDialog::CustomMessageLoop <- UIBaseDialog::ShowDialog: modal=1, title="Choose a package to open" <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1556

**Comment by getagrid** [comment]
Hey, I'm receiving the "bad allocation size" error whenever I'm trying to export anything from the valorant game files using umodel. I've set up numerous engine versions, Downloaded a variety of umodel versions to see if the problem was located in the version I'm using but apparently it's not. I'm not too sure if I'm missing out on some specific settings located in umodel or if there is a problem with the software. As you can see in the images, when the Error message pops up it's still pretending to load in the background while the export has clearly failed. Would love to get some help/know how to solve this.

Best Regards, Tristan 

![bad alc size](https://user-images.githubusercontent.com/89392839/130581936-4c35ee59-f345-4d47-b020-83e5460fc4d1.PNG)
![bad alc size loading](https://user-images.githubusercontent.com/89392839/130581954-cefa332b-3124-410a-9cea-0a9ba6d2701d.PNG)

**Comment by gildor2** [comment]
I see you're using UE4.27 setting. I think, if game (you didn't say the NAME of the game) is REALLY using release version of UE4.27 - it might not work because I didn't do final support for this engine version yet.
