### ISSUE TITLE
Bone reverse Z-orientation  when two child bone have same parent  bone

### ISSUE THREAD

**Issue by zhangjian076413** [gildor2/UEViewer#159]
Bone reverse Z-orientation  when two child bone have same parent  bone .
if i chose reorientation bones, the z-reverse fixed , but when l import anim thru PSA ,play animation 
then the z_reverse appear again.
so, i  print maxscript find out the orientation  is  wrong before exporting  from Umodel ,
 I wonder if mirror  operation lead to this situation.
please fix this issues

**Comment by gildor2** [comment]
Did you ever try ANIMATION with these "wrong bones", or just saying that bones doesn't look good in Max?

**Comment by zhangjian076413** [comment]
Bones doesn't look good in Max,the animation is perform correct. But the bone's end position which means orientation  is wrong when the human bones is symmetry，ons side of the child bones is reverse to opposite direction.
Will it cause anyproblem on  ue engine?

**Comment by gildor2** [comment]
This is not a problem at all. Engine doesn't know about bone end position - actually, bone is just a position and rotation (i.e. coordinate system). When UE Viewer or UE itself displays bones, it simply connects start of one bone with start of another bone, because there's no "bone end" term. 3ds Max behaves differently when displaying a skeleton.
