### ISSUE TITLE
UEViewer 64-bit

### ISSUE THREAD

**Issue by Goldermor** [gildor2/UEViewer#181]
Honestly, I think I'm really stupid.
I don't understand how to get the 64-bit version of the program.
There is some thing in the releases, but it just doesn't work...
the readme says about the building... why do I need to build a version? how can an ordinary user do this?
Why can't you just add a ready-made 64-bit version for download?

**Comment by gildor2** [comment]
You may build 64 bits from Visual Studio or Visual Studio Code. Or use command line with --64 option. "Ordinary users" doesn't have a github accounts, isn't it?
There was a long discussion about 32 vs 64 bits on the forum and not so long time ago on twitter.

**Comment by Goldermor** [comment]
I registered an account just to contact you xD
For the building, do I need to download the 64-bit port, or the code on the main page?

**Comment by gildor2** [comment]
"64 bit port" is just a git tag, it has test "Please note: this page exists only as placeholder for build files. For building UE Viewer yourself, just use recent git commit."
BTW most people don't need a 64-bit version. They thinks that when UModel says "bad allocation size" or something else, it's because of its 32-bitness, but actually this error happens because of unsupported game or bad umodel's startup settings.

**Comment by gildor2** [comment]
Just get the right dll. My twitter had a link several times.
