### ISSUE TITLE
Package merge functionality

### ISSUE THREAD

**Issue by cmbasnett** [gildor2/UEViewer#185]
Hi again!

We are working on our game that uses UT2004. In our workflow, we use feature branches to build out new functionality and then merge disparate branches together occasionally. It is a big hassle to merge the actual packages together though, requiring us to manually extract out the assets and then append them on to another version of the package.

Based on your knowledge of the package structure, would it be technically feasible to effectively merge two packages together (eg. two texture packages) into one programmatically? Our team would be very interested in helping develop this functionality for UEViewer if so.

Thanks!

**Comment by gildor2** [comment]
Hi
This would be a hard task even if you'd have the source code of UT2004 and consider making a commandlet (typical way of processing packages). You'd need not just to merge packages, but also update links in existing packages, so they'd reference to another package file.
Doing a separate tool (not using UE2 codebase) is a very hard task because in UE2 you can't just copy data of existing object - you should update references to other objects (index in import table), and even more - in UE2 these references has variable size ("compact index" structure).
